name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # master 分支有 push 行为时就触发这个 action

jobs:
  process_md:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: pip install pyyaml
    
    - name: Process Markdown files
      run: |
        python source/python/photo_edit.py
        python source/python/photo_move.py
      
    - name: Check if changes exist
      run: |
        git diff-index --quiet HEAD || touch .gitchanges
      id: check_changes
      
    - name: Commit and push changes
      run: |
        git config --global user.name "Charles-Hello"
        git config --global user.email "1140601003@qq.com"
        git add .
        git commit -m "Update Markdown files"
        git push https://${{ secrets.HEXO_DEPLOY }}@github.com/Charles-Hello/blog.git HEAD:main
      if: steps.check_changes.outputs.returncode == '0'


  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master # 使用专门部署 Hexo 到 GitHub pages 的 action
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }} # secret 名
          PUBLISH_REPOSITORY: Charles-Hello/Charles-Hello.github.io # 公共仓库，格式：GitHub 用户名/仓库名
          BRANCH: master # 
          PUBLISH_DIR: ./public # 部署 public 目录下的文件
