name: Process Markdown Files

on: [push]

jobs:
  process_md:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: pip install pyyaml
    
    - name: Process Markdown files
      run: |
        python source/python/photo_edit.py
        python source/python/photo_move.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "Charles-Hello"
        git config --global user.email "1140601003@qq.com"
        git add .
        git commit -m "Update Markdown files"
        git push
